### ISSUE TITLE
Update the location of ISO/TC211 xsd files in the OGC Schemas repository

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/architecture-dwg#30]
We have been [notified](https://github.com/INSPIRE-MIF/helpdesk/issues/73#issuecomment-991032921) that the location of ISO/TC211 xsd files has changed to https://schemas.isotc211.org

Below is a list of updates we would like to make to xsd files at [schemas.opengis.net](http://schemas.opengis.net) in order to reference the new location of the ISO/TC211 xsd files.

Please let us know by 21 January 2022, by replying on this thread, if you have any concerns about the updates.

**SCHEMAS_OPENGIS_NET/guf/1.0/pqm.xsd**

Line 18: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/ReadMe.txt**

Line 22: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gco/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gmd/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gmx/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gsr/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gss/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/gts/ReadMe.txt**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/srv/1.0/serviceMetadata.xsd**

Line 23: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd"

Line 24: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

**SCHEMAS_OPENGIS_NET/iso/19139/20070417/srv/1.0/serviceModel.xsd**

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd"

Line 14: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

**SCHEMAS_OPENGIS_NET/security/1.0/codelist/authentication.xml**

Line 7: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmx/1.0/gmx.xsd"

Line 8: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

Line 9: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd"

**Comment by cportele** [comment]
@ghobona - Regarding the two cases of

> Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd"

This should be replaced by "http://schemas.opengis.net/gml/3.2.1/gml.xsd", which is the authoritative location of the schema.

ISO 19136-1:2020 also states in Annex C, like GML 3.2.2:

> XML Schema documents with the GML schema are available online at: 
> 
> http://schemas.opengis.net/gml/3.2.1/

I have no idea why ISO/TC 211 published (again!) its own copy of the GML 3.2/19136-1 schemas...

In addition, the schema that ISO/TC 211 publishes is outdated, it is version 3.2.1.2, the current version of GML 3.2 in the OGC Schema Repository is 3.2.2.

(What is even more confusing is that I see that TC 211 have published another schema under 19136-1, which has nothing to do with the 19136-1 standard or OGC GML, but this has nothing to do with this issue.)

**Comment by heidivanparys** [comment]
> Regarding the two cases of
> 
> > Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd"
> 
> This should be replaced by "http://schemas.opengis.net/gml/3.2.1/gml.xsd", which is the authoritative location of the schema.
> 
> ISO 19136-1:2020 also states in Annex C, like GML 3.2.2:
> 
> > XML Schema documents with the GML schema are available online at:
> > http://schemas.opengis.net/gml/3.2.1/
> 
> I have no idea why ISO/TC 211 published (again!) its own copy of the GML 3.2/19136-1 schemas...
> 
> In addition, the schema that ISO/TC 211 publishes is outdated, it is version 3.2.1.2, the current version of GML 3.2 in the OGC Schema Repository is 3.2.2.
> 
> (What is even more confusing is that I see that TC 211 have published another schema under 19136-1, which has nothing to do with the 19136-1 standard or OGC GML, but this has nothing to do with this issue.)

(mentioning the TC 211 XMG Convenors, @ejbleys and @sptws001 to inform them about this issue)

**Comment by ejbleys** [comment]
Dear All
DO NOT USE 19136
ISO/TC211 recognises that the 19139 material should not be used. 
The ongoing existence of the 19136 XML schemas is due to an undertaking that ISO/TC211 will continue to make XML material available, even if the standard has been updated or withdrawn, hence 19136 will continue to be available and increasingly out of date.
The material in https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd <https://schemas.isotc211.org/schemas/19136/-/gml/1.0/gml.xsd> is as it was published way back when, it may have been ill conceived, but it was published as ISO/TC211 schemas, and so remains.

Fortunately TC 211 will not be attempting to update .../19136/… XML schemas, as that would make no sense at all, directing all users too use the http://schemas.opengis.net/gml/… <http://schemas.opengis.net/gml/3.2.1/> (currently 3.2.1set.
 
Yours sincerely
Evert
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ghobona** [comment]
SCHEMAS_OPENGIS_NET/guf/1.0/pqm.xsd

- [x] Line 18: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "http://schemas.opengis.net/gml/3.2.1/gml.xsd"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/ReadMe.txt

- [x] Line 22: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/gco/ReadMe.txt

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/gmd/ReadMe.txt

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

- [x] SCHEMAS_OPENGIS_NET/iso/19139/20070417/gmx/ReadMe.txt

Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/gsr/ReadMe.txt

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/gss/ReadMe.txt

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/gts/ReadMe.txt

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/" with "https://schemas.isotc211.org/schemas/19139/"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/srv/1.0/serviceMetadata.xsd

- [x] Line 23: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd"

- [x] Line 24: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

SCHEMAS_OPENGIS_NET/iso/19139/20070417/srv/1.0/serviceModel.xsd

- [x] Line 13: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd"

- [x] Line 14: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

SCHEMAS_OPENGIS_NET/security/1.0/codelist/authentication.xml

- [x] Line 7: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gmx/1.0/gmx.xsd"

- [x] Line 8: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" with "https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"

- [x] Line 9: Replace "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd" with "http://schemas.opengis.net/gml/3.2.1/gml.xsd"

**Comment by ghobona** [comment]
The update has been completed. This GitHub Issue will be closed on 2022-06-30.

**Comment by ejbleys** [comment]
Reason for re-publishing is that TC211 actively maintains all old versions. Republish was actually continue to publish as TC211 XMG no longer has maintenance on any space other than https://schemas.isotc211.org

Evert Bleys
