### ISSUE TITLE
Feedback to JSON-LD standard

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/architecture-dwg#7]
> The authors of this document perceive the current documentation of JSON-LD as confusing. That is why another approach in explaining how to use JSON-LD is exposed here.

W3C is starting up a working group to work on a new JSON-LD version. We should feed things like this back to them. That will be appreciated. 

Also, the problem with coordinates in GeoJSON-LD. 

We could use this issue to gather comments we have on JSON-LD and we can feed them back to W3C in various ways.

**Comment by ghobona** [comment]
E-mail sent to @gkellogg on March 7th, 2019. He is the editor of the [W3C JSON-LD community group report](https://www.w3.org/2018/jsonld-cg-reports/json-ld/).
